name: Build

on:
  # push:
  #   branches:
  #     - 'master'
  workflow_dispatch:

# env:
#   AZURE_WEBAPP_NAME: my-app-name    # set this to your application's name
#   AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
#   DOTNET_VERSION: '6.0.x'           # set this to the dot net version to use

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v4
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0 
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish "Test2.API/Test.API.csproj" -c Release --property:PublishDir='${{ github.workspace }}\app' 
          ls ${{ github.workspace }}\app

      # - name : Echo Build Details
      #   run: |
      #     touch ${{ github.workspace }}/version.txt
      #     echo ${{ github.run_id }} >> ${{ github.workspace }}/version.txt
          
      - name: Zip MDM Build artifacts
        run: |
          cd '${{ github.workspace }}/app'
          Compress-Archive -Path ./* -DestinationPath "${{ github.workspace }}\publish.zip" -Force 
          
      # - name: zip publish folder
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Artifacts
      #     path: | 
      #       ${{ github.workspace }}/app
      #       ${{ github.workspace }}/version.txt
      #     compression-level: 9
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
